Casting to class labels: 100%|█████████████████████| 10000/10000 [00:00<00:00, 565132.99 examples/s]
Map:   0%|                                                          | 0/8000 [00:00<?, ? examples/s]/Users/justn/Library/Caches/pypoetry/virtualenvs/ai-text-detect-3ocuaAWT-py3.11/lib/python3.11/site-packages/transformers/tokenization_utils_base.py:1617: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be deprecated in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
Map: 100%|█████████████████████████████████████████████| 8000/8000 [00:04<00:00, 1654.54 examples/s]
Map: 100%|█████████████████████████████████████████████| 2000/2000 [00:01<00:00, 1575.89 examples/s]
/Users/justn/Library/Caches/pypoetry/virtualenvs/ai-text-detect-3ocuaAWT-py3.11/lib/python3.11/site-packages/lightning/pytorch/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/justn/ai-text-detect/checkpoints exists and is not empty.

  | Name          | Type                               | Params | Mode
-----------------------------------------------------------------------------
0 | model         | PeftModelForSequenceClassification | 66.5 M | train
1 | train_metrics | MetricCollection                   | 0      | train
2 | valid_metrics | MetricCollection                   | 0      | train
3 | test_metrics  | MetricCollection                   | 0      | train
-----------------------------------------------------------------------------
702 K     Trainable params
65.8 M    Non-trainable params
66.5 M    Total params
265.943   Total estimated model params size (MB)
201       Modules in train mode
98        Modules in eval mode
Epoch 4:  95%|▉| 632/667 [07:59<00:26,  1.32it/s, v_num=zbfa, val_BinaryAccuracy_step=1.000, val_Bin
/Users/justn/Library/Caches/pypoetry/virtualenvs/ai-text-detect-3ocuaAWT-py3.11/lib/python3.11/site-packages/torch/amp/autocast_mode.py:265: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn(
                                                                                                    
`Trainer.fit` stopped: `max_epochs=5` reached.
